
name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tectonic
        run: curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh
        working-directory: /usr/local/bin

      - name: Cache Tectonic packages
        if: steps.graphics.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: tectonic
        with:
          path: ~/.cache/Tectonic
          key: Tectonic-${{ hashFiles('dist/**/.tex') }}
          restore-keys: Tectonic-

      - name: Build
        run: tectonic -X build

      - run: ls -a
